### ISSUE TITLE
Gimp Resynthesizer - Kubuntu 20.04 LTS

### ISSUE THREAD

**Issue by DominiqueFrt** [flathub/org.gimp.GIMP.Plugin.Resynthesizer#3]
Suite réinstallation GIMP with Discover the Plugin "Resynthesizer" does not install since Discover.
It must be installed online command line:
vieux_loup@Zalman:~$ flatpak install flathub org.gimp.GIMP.Plugin.Resynthesizer
Looking for matches…
Similar refs found for ‘org.gimp.GIMP.Plugin.Resynthesizer’ in remote ‘flathub’ (system):

runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-40
runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-3.36

Which do you want to use (0 to abort)? [0-2]: 1
    ID                                                    Branch            Op            Remote             Download

[✓] org.gimp.GIMP.Plugin.Resynthesizer.Locale             2-40              i             flathub            1.0 kB / 4,4 kB
[✓] org.gimp.GIMP.Plugin.Resynthesizer                    2-40              i             flathub                   111,0 kB / 141,5 kB

Installation complete.
vieux_loup@Zalman:~$

"Heal_selection" me returns the following error message:
Traceback (most recent call last):
File "/app/lib/gimp/2.0/python/gimpfu.py", line 740, in response
dialog.res = run_script(params)
File "/app/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
return apply(function, params)
File "/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found

**Comment by hfiguiere** [comment]
> File "/home/vieux_loup/plugin-heal-selection.py", line 148, in heal_selection

Not sure what's happening here, but this is not the path of the plugin. `.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/` should be empty.

**Comment by hfiguiere** [comment]
Feels like it is a duplicate of #1

**Comment by DominiqueFrt** [comment]
1 - TRACE PURGE GIMP 2.10.18 
      `administrateur@Zalman:~$ sudo apt purge -f gimp*
[sudo] Mot de passe de administrateur : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de gimp-refocus pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-common pour l'expression rationnelle « gimp* »
Note : sélection de gimp-dds pour l'expression rationnelle « gimp* »
Note : sélection de gimp-plugin-registry pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help pour l'expression rationnelle « gimp* »
Note : sélection de gimp-gap pour l'expression rationnelle « gimp* »
Note : sélection de gimp1.2-cbmplugs pour l'expression rationnelle « gimp* »
Note : sélection de gimp-data pour l'expression rationnelle « gimp* »
Note : sélection de gimp-texturize pour l'expression rationnelle « gimp* »
Note : sélection de gimp-gluas pour l'expression rationnelle « gimp* »
Note : sélection de gimp pour l'expression rationnelle « gimp* »
Note : sélection de gimp-svg pour l'expression rationnelle « gimp* »
Note : sélection de gimp-dcraw pour l'expression rationnelle « gimp* »
Note : sélection de gimp-normalmap pour l'expression rationnelle « gimp* »
Note : sélection de gimp-gmic pour l'expression rationnelle « gimp* »
Note : sélection de gimp-helpbrowser pour l'expression rationnelle « gimp* »
Note : sélection de gimp-resynthesizer pour l'expression rationnelle « gimp* »
Note : sélection de gimp-gutenprint pour l'expression rationnelle « gimp* »
Note : sélection de gimp1.3-cbmplugs pour l'expression rationnelle « gimp* »
Note : sélection de gimp-lensfun pour l'expression rationnelle « gimp* »
Note : sélection de gimp-cbmplugs pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-ca pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-de pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-el pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-en pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-es pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-fr pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-it pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-ja pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-ko pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-nl pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-nn pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-pt pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-ru pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-sl pour l'expression rationnelle « gimp* »
Note : sélection de gimp-help-sv pour l'expression rationnelle « gimp* »
Note : sélection de gimp-ufraw pour l'expression rationnelle « gimp* »
Note : sélection de gimp-save-for-web pour l'expression rationnelle « gimp* »
Note : sélection de gimp-data-extras pour l'expression rationnelle « gimp* »
Le paquet « gimp1.2-cbmplugs » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp1.3-cbmplugs » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-helpbrowser » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-refocus » n'est pas installé, et ne peut donc être supprimé
Note : sélection de « gimp-plugin-registry » au lieu de « gimp-resynthesizer »
Note : sélection de « gimp-plugin-registry » au lieu de « gimp-save-for-web »
Le paquet « gimp-ufraw » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-svg » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-cbmplugs » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-data-extras » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-dcraw » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-dds » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-gap » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-gluas » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-gmic » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-gutenprint » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-ca » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-de » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-el » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-en » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-es » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-it » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-ja » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-ko » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-nl » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-nn » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-pt » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-ru » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-sl » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-help-sv » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-normalmap » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-plugin-registry » n'est pas installé, et ne peut donc être supprimé
Le paquet « gimp-texturize » n'est pas installé, et ne peut donc être supprimé
Les paquets suivants seront ENLEVÉS :
  gimp-data* gimp-help-common* gimp-help-fr* gimp-lensfun*
0 mis à jour, 0 nouvellement installés, 4 à enlever et 0 non mis à jour.
Après cette opération, 93,7 Mo d'espace disque seront libérés.
Souhaitez-vous continuer ? [O/n] o
(Lecture de la base de données... 334004 fichiers et répertoires déjà installés.)
Suppression de gimp-data (2.10.18-1) ...
Suppression de gimp-help-fr (2.8.2-2ubuntu1) ...
Suppression de gimp-help-common (2.8.2-2ubuntu1) ...
Suppression de gimp-lensfun (0.2.4-1.1) ...
Traitement des actions différées (« triggers ») pour doc-base (0.10.9) ...
Traitement de 1 fichier de documentation supprimé…
Traitement des actions différées (« triggers ») pour man-db (2.9.1-1) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-2) ...
(Lecture de la base de données... 327599 fichiers et répertoires déjà installés.)
Purge des fichiers de configuration de gimp-data (2.10.18-1) ...
administrateur@Zalman:~$ `

2 - SUPPRESSION OF GIMP RESYNTHESIZER WITH KUBUNTU 20.04 Discover
3 - SUPPRESSION OF GIMP 2.10.24 FLATPACK with /home/vieux_loup/.var/app/org.gimp.gimp
4 - SUPPRESSION OF "/HOME/VIEUX_LOUPE/.VAR/App/org.GIMP.GIMP"
5 - Reinstalling GIMP and Resynthesizer Flatpak with Kubuntu 20.04 Discover

6 - Message error heal_slection: 

Traceback (most recent call last):
  File "/app/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/app/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found

![~⁄ var⁄app](https://user-images.githubusercontent.com/42612895/113472697-3f53db00-9465-11eb-8e61-f7877d1a6607.png)
![GIMP_1](https://user-images.githubusercontent.com/42612895/113472707-467ae900-9465-11eb-9f94-5a01bf940012.png)
![GIMP_2](https://user-images.githubusercontent.com/42612895/113472716-5e526d00-9465-11eb-85d0-053837a678a0.png)
![GIMP_3](https://user-images.githubusercontent.com/42612895/113472731-71653d00-9465-11eb-8cf3-d11b36fb8496.png)
![GIMP_4](https://user-images.githubusercontent.com/42612895/113472740-7cb86880-9465-11eb-82db-ea1488ba9cf0.png)
![Discover](https://user-images.githubusercontent.com/42612895/113472819-d7ea5b00-9465-11eb-8f45-e608dbeb3abf.png)

**Comment by hfiguiere** [comment]
I have no idea what's happening and I don't have KUbuntu to try it.

(I don't even know what KUbuntu Discover is, but I assume it's the equivalent of GNOME Software)

**Comment by hfiguiere** [comment]
From the step you describe `~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins` should be empty or inexistent. 

Can you check it's actually the case?

**Comment by DominiqueFrt** [comment]
`vieux_loup@Zalman:~$ flatpak install flathub org.gimp.GIMP.Plugin.Resynthesizer
Looking for matches…
Similar refs found for ‘org.gimp.GIMP.Plugin.Resynthesizer’ in remote ‘flathub’ (system):

   1) runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-40
   2) runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-3.36

Which do you want to use (0 to abort)? [0-2]: 1
Skipping: org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-40 is already installed
vieux_loup@Zalman:~$ 
`
![Dolphin](https://user-images.githubusercontent.com/42612895/113484375-494afd80-94a8-11eb-83d6-7347cf8bca9f.png)
![Resyntesizer](https://user-images.githubusercontent.com/42612895/113484563-48669b80-94a9-11eb-9500-584c5ba0a4f6.png)

**Comment by hfiguiere** [comment]
so it's working now?

**Comment by DominiqueFrt** [comment]
It's not working.
![gimp](https://user-images.githubusercontent.com/42612895/113488776-5d025e00-94c0-11eb-90ac-b59d19a182cb.png)

**Comment by hfiguiere** [comment]
I'm gonna guess it still the same error message, but it's truncated because screenshot....
I still don't understand why it is trying to load them from the empty directory.

What are the path for the plugins?
There are listed in Preferences > Folders > Plug-ins

**Comment by bootchk** [comment]
It is strange because you show a screenshot of the Resynthesizer control panel ( Filters>Map>Resynthesize ) working.
That is the file "resynthesizer-gui" which is not the same as the file "resynthesizer", but they should both be in the same directory.
I don't understand how one would install but not the other.
The file "resynthesizer" is the one that "Heal selection" calls.

You might try to start GIMP in a console with the "--verbose" option.  Then any error messages would print on the console.
When GIMP starts, it "queries" the plugins.  If there are errors at that time, then later the plugin would not work.
In other words, if the "resynthesizer" file cannot be queried at start time, you would not know when running the GUI because those errors are silent, but if you start GIMP from a console, you might see an error message something like "failed to query plugin resynthesizer".  Only the plugins that are successfully queried are in the PDB.  If they fail to query, later you get the message like you got, like "procedure not found" which means "not found in the PDB" and does not mean "not found in the file system."

**Comment by hfiguiere** [comment]
What puzzle me here is that error show that GIMP tries to locate the plugin where it should not be, and that the previous screenshot seems to show there is nothing there in `~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins` (hence shouldn't even try to locate it as GIMP rescan plugins on startup).

That python file should be in `/app/extensions/plug-ins` (that's inside the sandbox so you can't really see it here).

As to why there would be an error, the `resynthesizer` binary is either not found or fail to load, and that the one registering the functions the python script is trying to load.

**Comment by bootchk** [comment]
See Gimp #3349.  Still open and discussion might be relevant but I have not yet reread it carefully.

**Comment by hfiguiere** [comment]
> See Gimp #3349. Still open and discussion might be relevant but I have not yet reread it carefully.

https://gitlab.gnome.org/GNOME/gimp/-/issues/3349

**Comment by hfiguiere** [comment]
Just to clarify, with the Flatpak extension resynthesizer is installed `/app/extensions/Resynthesizer/plug-ins` and flatpak link this into `/app/extensions/plug-ins` which GImp finds properly. That GIMP issue above predate this.

(this is GIMP 2, GIMP 3 (2.99) use something a bit different, but there is only GMic for now)

**Comment by hfiguiere** [comment]
And if Gimp find something in `.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/plugin-heal-selection.py` then there is something wrong because there should be nothing, or at least not Resynthesizer.

**Comment by DominiqueFrt** [comment]
What are the path for the plugins?
There are listed in Preferences > Folders > Plug-ins
__________________________________________________
![image](https://user-images.githubusercontent.com/42612895/113500347-800f2b00-951d-11eb-9492-6f57abec6037.png)
_________________________________________________________________________________________
`vieux_loup@Zalman:~$ flatpak --verbose run org.gimp.GIMP//stable
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/vieux_loup/.local/share/flatpak
F: Opening user flatpak installation at path /home/vieux_loup/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/vieux_loup/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 1449902516
F: Allocated instance id 1891287280
F: Add defaults in dir /org/gimp/GIMP/
F: Add locks in dir /org/gimp/GIMP/
F: Allowing dri access
F: Allowing host-fs access
F: Allowing x11 access
F: Running 'bwrap --args 34 xdg-dbus-proxy --args=36'
F: Running 'bwrap --args 34 gimp-2.10'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-uncrop.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-resynth-sharpen.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-heal-selection.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-resynth-fill-pattern.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-render-texture.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-heal-transparency.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-map-style.py'
Skipping duplicate plug-in: '/app/extensions/plug-ins/resynthesizer'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-resynth-enlarge.py'
GIMP-Erreur: Unable to run plug-in "resynthesizer-gui"
(/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/resynthesizer-gui)

Échec à l’exécution du processus enfant « /home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/resynthesizer-gui » (Aucun fichier ou dossier de ce type)

gimp-2.10: LibGimpBase-AVERTISSEMENT: gimp-2.10: gimp_wire_read(): error
Unable to read initialization file script-fu.init
Plug-in "script-fu"
(/app/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-fake-hdr-effect" with a full menu path "<Image>/Script-Fu/Enhance/Fake HDR Effect..." as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/app/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-fake-hdr-effect-plus" with a full menu path "<Image>/Script-Fu/Enhance/Fake HDR Effect plus..." as menu label, this deprecated and will be an error in GIMP 3.0
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
gimp_color_transform_new: using babl for 'RTv4_sRGB' -> 'GIMP built-in sRGB'
gimp_color_transform_new: using babl for 'GIMP built-in sRGB' -> 'RTv4_sRGB'
gimp_color_transform_new: using babl for 'RTv4_sRGB' -> 'GIMP built-in sRGB'
gimp_color_transform_new: using babl for 'GIMP built-in sRGB' -> 'RTv4_sRGB'
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accuracy desired and cluts are present
Traceback (most recent call last):
  File "/app/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/app/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
gimp.error: procedure not found
gimp_color_transform_new: error making dest format: ASUS VS228 #1 2018-12-05 10-18 120cdm2 D6500 2.2 M-S XYZLUT+MTX: use lcms, accurac`

**Comment by bootchk** [comment]
@DominiqueFrt  Thanks.

You have posted a screenprint for the *scripts* paths, but we need the paths for *plugins*.  Scripts are for ScriptFu plugins in the Scheme language with ".scm" suffix.  Plugins are binaries (like resynthesizer) or Python files with suffix ".py".  Choose Edit>Preferences>PluginFolders>Plugins instead of >Scripts.

When I do, I get:

![Screenshot from 2021-04-04 09-29-54](https://user-images.githubusercontent.com/702481/113510361-87880180-9528-11eb-87ac-433a2aa6270e.png)

If your paths are not similar to the above, click on the "Reset plug-in Folders" button in the upper right, which should change the list of paths to a default, like mine.

Also, the text from --verbose  shows something is not correct.

```
Skipping duplicate plug-in: '/app/extensions/plug-ins/resynthesizer'
Skipping duplicate plug-in: '/app/extensions/plug-ins/plugin-resynth-enlarge.py'
GIMP-Erreur: Unable to run plug-in "resynthesizer-gui"
(/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/resynthesizer-gui)
```
It shows that GIMP has already queried a duplicate from some other path.  So you need to change the paths, or delete the duplicates.

However, it is strange that resynthesizer-gui is not recognized as a duplicate.  Maybe that is a bug in GIMP since "resynthesizer" and "resynthesizer-gui" are so similar names, maybe GIMP is confused.  Or maybe you have a duplicate of the others, but not a duplicate resynthesizer-gui.

"Unable to run..." does mean that the resynthesizer-gui" failed to register, but you have already shown a screenshot of it running.
Which is strange.  My theory is that there is a duplicate, but GIMP has a bug in its filtering of duplicate filenames, and tried to query it again, which would then fail since it was already registered in the PDB.   Again, it would be best if you eliminate the duplicates.

```
gimp-2.10: LibGimpBase-AVERTISSEMENT: gimp-2.10: gimp_wire_read(): error
Unable to read initialization file script-fu.init 
```
This is a separate issue.  I think this was fixed in GIMP 2.10.24 (released a few days ago.)   See GIMP issue #6018 which is for the Mac platform, but might be relevant to the flatpak?  Are you running 2.10.24?

I see above something about a purge (I don't understand the Discover tool on Kubuntu.)
```
3 - SUPPRESSION OF GIMP 2.10.24 FLATPACK with /home/vieux_loup/.var/app/org.gimp.gimp
```
Does that mean it failed to install 2.10.24?  In English, "suppression" means "hold back" or "prevent."

**Comment by hfiguiere** [comment]
> ```
> 3 - SUPPRESSION OF GIMP 2.10.24 FLATPACK with /home/vieux_loup/.var/app/org.gimp.gimp
> ```
> 
> 
> Does that mean it failed to install 2.10.24?  In English, "suppression" means "hold back" or "prevent."

It's loose translation of delete.
(As a native French speaker I can never understand translated software, or anything about CS translated in French, really)

**Comment by hfiguiere** [comment]
These are the wrong path you showed. I asked for the plugin path, not the script path.

But my conclusion is that there are things in `/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins`.

**Comment by DominiqueFrt** [comment]
Suite Uninstall and reinstall GIMP:
- Can not open an image
-Resynthesizer is no longer presented in Filtres-Cartes

![Screenshot_20210405_095715](https://user-images.githubusercontent.com/42612895/113551749-71944280-95f5-11eb-82de-795d707e7b41.png)

`vieux_loup@Zalman:~$ flatpak list
Name                                                Application ID                                            Version            Branch            Installation
MakeMKV                                             com.makemkv.MakeMKV                                       1.16.1             stable            system
MKVToolNix                                          org.bunkus.mkvtoolnix-gui                                 55.0.0             stable            system
default                                             org.freedesktop.Platform.GL.default                                          19.08             system
default                                             org.freedesktop.Platform.GL.default                                          20.08             system
nvidia-450-102-04                                   org.freedesktop.Platform.GL.nvidia-450-102-04                                1.4               system
openh264                                            org.freedesktop.Platform.openh264                         2.1.0              2.0               system
OCRFeeder                                           org.gnome.OCRFeeder                                       0.8.3              stable            system
GNOME Application Platform version 3.36             org.gnome.Platform                                                           3.36              system
Breeze Gtk theme                                    org.gtk.Gtk3theme.Breeze                                                     3.22              system
Adwaita theme                                       org.kde.KStyle.Adwaita                                                       5.15              system
KDE Application Platform                            org.kde.Platform                                                             5.15              system


vieux_loup@Zalman:~$ flatpak list --app
Name              Application ID                   Version        Branch       Installation
MakeMKV           com.makemkv.MakeMKV              1.16.1         stable       system
MKVToolNix        org.bunkus.mkvtoolnix-gui        55.0.0         stable       system
OCRFeeder         org.gnome.OCRFeeder              0.8.3          stable       system


vieux_loup@Zalman:~$ flatpak uninstall --unused
Nothing unused to uninstall


vieux_loup@Zalman:~$ flatpak list
Name                                                Application ID                                            Version            Branch            Installation
MakeMKV                                             com.makemkv.MakeMKV                                       1.16.1             stable            system
MKVToolNix                                          org.bunkus.mkvtoolnix-gui                                 55.0.0             stable            system
default                                             org.freedesktop.Platform.GL.default                                          19.08             system
default                                             org.freedesktop.Platform.GL.default                                          20.08             system
nvidia-450-102-04                                   org.freedesktop.Platform.GL.nvidia-450-102-04                                1.4               system
openh264                                            org.freedesktop.Platform.openh264                         2.1.0              2.0               system
Éditeur d’image GIMP                                org.gimp.GIMP                                             2.10.24            stable            system
Manual                                              org.gimp.GIMP.Manual                                                         2.10              system
OCRFeeder                                           org.gnome.OCRFeeder                                       0.8.3              stable            system
GNOME Application Platform version 3.36             org.gnome.Platform                                                           3.36              system
GNOME Application Platform version 40               org.gnome.Platform                                                           40                system
Breeze Gtk theme                                    org.gtk.Gtk3theme.Breeze                                                     3.22              system
Adwaita theme                                       org.kde.KStyle.Adwaita                                                       5.15              system
KDE Application Platform                            org.kde.Platform                                                             5.15              system


vieux_loup@Zalman:~$ flatpak list --app
Name                         Application ID                    Version         Branch        Installation
MakeMKV                      com.makemkv.MakeMKV               1.16.1          stable        system
MKVToolNix                   org.bunkus.mkvtoolnix-gui         55.0.0          stable        system
Éditeur d’image GIMP         org.gimp.GIMP                     2.10.24         stable        system
OCRFeeder                    org.gnome.OCRFeeder               0.8.3           stable        system


vieux_loup@Zalman:~$ flatpak install flathub org.gimp.GIMP.Plugin.Resynthesizer
Looking for matches…
Similar refs found for ‘org.gimp.GIMP.Plugin.Resynthesizer’ in remote ‘flathub’ (system):

   1) runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-40
   2) runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-3.36

Which do you want to use (0 to abort)? [0-2]: 1


        ID                                                    Branch            Op            Remote             Download
 1. [✓] org.gimp.GIMP.Plugin.Resynthesizer.Locale             2-40              i             flathub            1.0 kB / 4,4 kB
 2. [✓] org.gimp.GIMP.Plugin.Resynthesizer                    2-40              i             flathub                   111,0 kB / 141,5 kB

Installation complete.
vieux_loup@Zalman:~$ `

![image](https://user-images.githubusercontent.com/42612895/113552004-ce8ff880-95f5-11eb-941b-928bae10cfc2.png)
![image](https://user-images.githubusercontent.com/42612895/113552137-039c4b00-95f6-11eb-8d38-0819061e6aed.png)

**Comment by hfiguiere** [comment]
As metionned in https://github.com/flathub/org.gimp.GIMP.Plugin.Resynthesizer/issues/3#issuecomment-813038462

Click on "Reinitialiser les dossier..." as seen in your screenshot above.

**Comment by DominiqueFrt** [comment]
![image](https://user-images.githubusercontent.com/42612895/113592927-120a5700-9636-11eb-9863-3943d0bfe944.png)
![Gimp2](https://user-images.githubusercontent.com/42612895/113593083-4847d680-9636-11eb-8f3e-f64ce2f4b355.png)
![gimp](https://user-images.githubusercontent.com/42612895/113593234-788f7500-9636-11eb-8718-33bb6a1ed46b.png)
![image](https://user-images.githubusercontent.com/42612895/113593779-1aaf5d00-9637-11eb-9373-68ac051400d6.png)
![image](https://user-images.githubusercontent.com/42612895/113593909-45011a80-9637-11eb-85b4-b15cf6dea745.png)
![image](https://user-images.githubusercontent.com/42612895/113594030-6b26ba80-9637-11eb-934d-b87ab0fd1b6d.png)

**Comment by hfiguiere** [comment]
So your screenshot of Dolphin is lying. How about the output of `find ~/.var/app/org.gimp.GIMP/config/GIMP`, and not as a screenshot?

**Comment by hfiguiere** [comment]
that's in the shell/terminal in case it wasn't clear.

**Comment by DominiqueFrt** [comment]
`vieux_loup@Zalman:~$ find ~/.var/app/org.gimp.GIMP/config/GIMP
/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP
vieux_loup@Zalman:~$ find ~/.var/app/org.gimp.GIMP/config/GIMP/config
find: ‘/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP/config’: Aucun fichier ou dossier de ce type
vieux_loup@Zalman:~$ find /app
find: ‘/app’: Aucun fichier ou dossier de ce type
vieux_loup@Zalman:~$ `

**Comment by DominiqueFrt** [comment]
Works with an "Administrator" account
Does not work with a "User" account

**Comment by hfiguiere** [comment]
> Works with an "Administrator" account
> Does not work with a "User" account

that's because the root user has a different home directory.

`~/.var/app/org.gimp.GIMP/config/GIMP` should not be empty, but since it is, definitely Gimp shouldn't find a plugin in there (like your error message say it does - as it indicate the python execution error at line 148, which if the file didn't exist wouldn't be happening). But this contradict your last screenshot that show there is `~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins` but doesn't show me its content. (it should be empty)

`~/.var/app/org.gimp.GIMP/config/GIMP/config` shouldn't exist, I didn't ask for it either.

`/app` shouldn't exist either outside of the sandbox, I didn't ask for it either.

I'm not sure what's happening here.

**Comment by hfiguiere** [comment]
> But this contradict your last screenshot that show there is `~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins` but doesn't show me its content. (it should be empty)

When I said "should be empty", it's the default state after launching GIMP (flatpak) the first time.

**Comment by DominiqueFrt** [comment]
/home/vieux_loup/.var/app/org.gimp.GIMP/config/GIMP and /home/administrateur/.var/app/org.gimp.GIMP/config/GIMP are empty in the file manager.
